- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  user: ubuntu
  vars:
    keypair: itrust_aws_key
    instance_type: t2.micro
    security_group: launch-wizard-2
    image: ami-43391926
    region: us-east-2
  tasks:

    # - name : Install pip
    #   apt: pkg=python-pip update_cache=yes state=present
    #   become: true
      
    - name: Install boto and boto3
      pip:
        name: "{{ item }}"
      with_items:
        - boto
        - boto3

    # # private key
    # - name: Creates key {{keypair}}
    #   ec2_key:
    #     name: "{{keypair}}"
    #     region: "{{region}}"
    #   register: ec2_key

    # - name: Save private key
    #   copy: content="{{ ec2_key.key.private_key }}" dest="{{keypair}}" mode=0777
    #   when: ec2_key.changed

    - name: Launch instance
      ec2:
         aws_access_key: AKIAIH3HKF34YODFTDTA
         aws_secret_key: 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
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-d8fcdba3
         assign_public_ip: yes
         instance_tags:
            Name: Nomad
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
        ansible_ssh_user: ubuntu
        ansible_ssh_private_key_file: "{{keypair}}.pem"
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 1000
        state: started
      with_items: "{{ ec2.instances }}"

    - debug:
        msg: "Instances: {{ ec2.instances }}"
      ignore_errors: yes