git_repo: https://github.com/kulkarnisneha/checkbox.io.git
checkbox_dest_home_path: /home/{{ansible_ssh_user}}/Checkbox/checkbox.io/
nginx_sites_path: /etc/nginx/sites-enabled/default
nginx_config_path: /etc/nginx/nginx.conf
env_vars:
  MONGO_PORT: "3002"
  MONGO_IP: "localhost"
  MONGO_USER: "admin"
  MONGO_PASSWORD: "admin"
  MAIL_USER: "skkulkar"
  MAIL_PASSWORD: "pass123"
  MAIL_SMTP: "smtp.gmail.com"