## Redis Master
- name: Setting up redis master
  hosts: localhost
  user: ubuntu
  vars:
    group_name: redis_master
  tasks:

  - name : Provision aws instance
    include: aws.yml
    vars:
      keypair: checkbox_aws_key
      instance_type: t2.micro
      security_group: launch-wizard-2
      image: ami-43391926
      region: us-east-2

  - set_fact: redis_master_ip={{ec2.instances[0].public_ip}}

- name: Configure redis master
  hosts: redis_master
  become: True
  gather_facts: True
  vars:
    checkbox_src_home_path: /home/{{ansible_ssh_user}}/Checkbox/checkbox.io/
  roles:
    - configure_redis_master
    - checkbox

## Redis Slave

- name: Setting up redis slave
  hosts: localhost
  user: ubuntu
  vars:
    group_name: redis_slave
  tasks:

  - name : Provision aws instance
    include: aws.yml
    vars:
      keypair: checkbox_aws_key
      instance_type: t2.micro
      security_group: launch-wizard-2
      image: ami-43391926
      region: us-east-2

- name: Configure redis slave
  hosts: redis_slave
  become: True
  gather_facts: True
  vars:
    redis_master_ip: "{{hostvars.localhost.redis_master_ip}}"
    checkbox_src_home_path: /home/{{ansible_ssh_user}}/Checkbox/checkbox.io/
  tasks:
    - debug:
        msg: "{{redis_master_ip}}"
  roles:
    - configure_redis_slave
    - checkbox

### CANARY

- name: Setting up canary server
  hosts: localhost
  user: ubuntu
  vars:
    group_name: canary
  tasks:

  - name : Provision aws instance
    include: aws.yml
    vars:
      keypair: checkbox_aws_key
      instance_type: t2.micro
      security_group: launch-wizard-2
      image: ami-43391926
      region: us-east-2

  - set_fact: canary_ip={{ec2.instances[0].public_ip}}
  # - set_fact: canary_ip=18.216.5.154

- name: Configure canary server
  hosts: canary
  become: True
  gather_facts: True
  vars:
    redis_master_ip: "{{hostvars.localhost.redis_master_ip}}"
    checkbox_src_home_path: /home/{{ansible_ssh_user}}/Checkbox/checkbox.io/
  roles:
    - configure_redis_slave
    - checkbox

### PRODUCTION

- name: Setting up production server
  hosts: localhost
  user: ubuntu
  vars:
    group_name: production
  tasks:

  - name : Provision aws instance
    include: aws.yml
    vars:
      keypair: checkbox_aws_key
      instance_type: t2.micro
      security_group: launch-wizard-2
      image: ami-43391926
      region: us-east-2

  - set_fact: production_ip={{ec2.instances[0].public_ip}}
#   # - set_fact: production_ip=18.217.20.129

- name: Configure production server
  hosts: production
  become: True
  gather_facts: True
  vars:
    redis_master_ip: "{{hostvars.localhost.redis_master_ip}}"
    checkbox_src_home_path: /home/{{ansible_ssh_user}}/Checkbox/checkbox.io/
  roles:
    - configure_redis_slave
    - checkbox

### PROXY

- name: Setting up proxy server
  hosts: localhost
  user: ubuntu
  vars:
    group_name: proxies
  tasks:

  - name : Provision aws instance
    include: aws.yml
    vars:
      keypair: checkbox_aws_key
      instance_type: t2.micro
      security_group: launch-wizard-2
      image: ami-43391926
      region: us-east-2

- name: Configure proxy server
  hosts: proxies
  become: True
  gather_facts: True
  vars:
    canary_ip: "{{hostvars.localhost.canary_ip}}"
    production_ip: "{{hostvars.localhost.production_ip}}"
    redis_master_ip: "{{hostvars.localhost.redis_master_ip}}"
    checkbox_src_home_path: /home/{{ansible_ssh_user}}/Checkbox/checkbox.io/
  roles:
    - configure_redis_slave
    - checkbox
    - proxy

### Nomad Server

- name: Setting up nomad server
  hosts: localhost
  user: ubuntu
  vars:
    group_name: nomad_server
  tasks:

  - name : Provision aws instance
    include: aws.yml
    vars:
      keypair: checkbox_aws_key
      instance_type: t2.micro
      security_group: launch-wizard-2
      image: ami-43391926
      region: us-east-2

- name: Configure nomad server
  hosts: nomad_server
  become: True
  gather_facts: True
  vars:
    redis_master_ip: "{{hostvars.localhost.redis_master_ip}}"
    checkbox_src_home_path: /home/{{ansible_ssh_user}}/Checkbox/checkbox.io/
  tasks:
    - debug:
        msg: "{{redis_master_ip}}"
  roles:
    - configure_redis_slave
    - checkbox

### Nomad Client 1

- name: Setting up nomad client 1
  hosts: localhost
  user: ubuntu
  vars:
    group_name: nomad_client
  tasks:

  - name : Provision aws instance
    include: aws.yml
    vars:
      keypair: checkbox_aws_key
      instance_type: t2.micro
      security_group: launch-wizard-2
      image: ami-43391926
      region: us-east-2

- name: Configure nomad client 1
  hosts: nomad_client
  become: True
  gather_facts: True
  vars:
    redis_master_ip: "{{hostvars.localhost.redis_master_ip}}"
    checkbox_src_home_path: /home/{{ansible_ssh_user}}/Checkbox/checkbox.io/
  tasks:
    - debug:
        msg: "{{redis_master_ip}}"
  roles:
    - configure_redis_slave
    - checkbox

  ### Nomad Client 2

- name: Setting up nomad client 2
  hosts: localhost
  user: ubuntu
  vars:
    group_name: nomad_client
  tasks:

  - name : Provision aws instance
    include: aws.yml
    vars:
      keypair: checkbox_aws_key
      instance_type: t2.micro
      security_group: launch-wizard-2
      image: ami-43391926
      region: us-east-2

- name: Configure nomad client 2
  hosts: nomad_client
  become: True
  gather_facts: True
  vars:
    redis_master_ip: "{{hostvars.localhost.redis_master_ip}}"
    checkbox_src_home_path: /home/{{ansible_ssh_user}}/Checkbox/checkbox.io/
  tasks:
    - debug:
        msg: "{{redis_master_ip}}"
  roles:
    - configure_redis_slave
    - checkbox